exec_timeout_secs: 3600

# Mark a failure as a system/bootstrap failure (purple box) rather then a task
# failure by default.
# Actual testing tasks are marked with `type: test`
command_type: system

# Ensure that setup and teardown is working as expected.
pre_error_fails_task: true
pre_timeout_secs: 1800 # 5 minutes
post_error_fails_task: true
post_timeout_secs: 1800 # 5 minutes

include:
  - filename: .evergreen/functions.yml

pre:
  - func: setup
  - func: bootstrap mongo-orchestration

post:
  - func: teardown

tasks:
  - name: run-tests
    commands:
      - func: "run unit tests"
  - name: run-encryption-tests
    commands:
      - func: "start csfle servers"
      - func: "run encryption tests"
      - func: "teardown csfle"
  - name: perf-tests
    commands:
      - func: "run performance tests"
      - func: "attach performance test results"
      - func: "send dashboard data"

buildvariants:
  - name: tests-7-noauth-nossl
    display_name: Run Tests 7.0 NoAuth NoSSL
    run_on: rhel87-small
    expansions:
      MONGODB_VERSION: "7.0"
      TOPOLOGY: server
      AUTH: "noauth"
      SSL: "nossl"
    tasks:
      - name: run-tests

  - name: tests-7-auth-ssl
    display_name: Run Tests 7.0 Auth SSL
    run_on: rhel87-small
    expansions:
      MONGODB_VERSION: "7.0"
      TOPOLOGY: server
      AUTH: "auth"
      SSL: "ssl"
    tasks:
      - name: run-tests

  - name: tests-8-noauth-nossl
    display_name: Run Tests 8.0 NoAuth NoSSL
    run_on: rhel87-small
    expansions:
      MONGODB_VERSION: "8.0"
      TOPOLOGY: server
      AUTH: "noauth"
      SSL: "nossl"
    tasks:
      - name: run-tests

  - name: tests-8-auth-ssl
    display_name: Run Tests 8.0 Auth SSL
    run_on: rhel87-small
    expansions:
      MONGODB_VERSION: "8.0"
      TOPOLOGY: server
      AUTH: "auth"
      SSL: "ssl"
    tasks:
      - name: run-tests

  - name: tests-8-qe-local
    display_name: Run Tests 8.2 QE local KMS
    run_on: rhel87-small
    expansions:
      MONGODB_VERSION: "8.2"
      TOPOLOGY: replica_set
      DJANGO_SETTINGS_MODULE: "encrypted_settings"
    tasks:
      - name: run-encryption-tests

  - name: tests-8-qe-aws
    display_name: Run Tests 8.2 QE AWS KMS
    run_on: rhel87-small
    expansions:
      MONGODB_VERSION: "8.2"
      TOPOLOGY: replica_set
      DJANGO_SETTINGS_MODULE: "encrypted_aws_settings"
    tasks:
      - name: run-encryption-tests

  - name: performance-benchmarks
    display_name: Performance Benchmarks
    run_on:
      - rhel90-dbx-perf-large
    batchtime: 1440
    tasks:
      - name: perf-tests
