# Generated by Django 5.2.4.dev20250616223441 on 2025-07-10 07:34

from django.db import migrations, models

import django_mongodb_backend.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    django_mongodb_backend.fields.ObjectIdAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="name")),
                (
                    "ssn",
                    django_mongodb_backend.fields.EncryptedCharField(
                        max_length=11,
                        queries=[
                            {"contention": 1, "queryType": "equality"},
                            {"precision": 3, "queryType": "range", "sparsity": 2},
                        ],
                        verbose_name="ssn",
                    ),
                ),
            ],
            options={
                "required_db_features": {"supports_queryable_encryption"},
            },
        ),
    ]
